language: bash

cache:
  directories:
  - "${HOME}/bin"

env:
  global:
  - PATH="${HOME}/bin
  - TF_VERSION="0.12.21"

before_install:
  - if ! terraform version ; then
      mkdir -p "${HOME}/bin"
      pushd ;
      curl -sSL
        -o terraform.zip
        "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" ;
      unzip terraform.zip ;
      mv -v terraform "${HOME}/bin/terraform" ;
      popd ;
      terraform version ;
    fi
  - ssh-keygen -b 2048 -t rsa -q -N "" -f ~/.ssh/id_rsa

script:
  - for cloud in aws azure gcp openstack ovh; do
      terraform init $cloud;
      terraform validate $cloud;
      sed -i 's;git::https://github.com/ComputeCanada/magic_castle.git//;../../;g' examples/$cloud/main.tf;
      terraform init examples/$cloud;
      terraform validate examples/$cloud;
    done
  - terraform init dns/cloudflare
  - terraform validate dns/cloudflare -var email="email@example.com" -var token="1234"
  - terraform init dns/gcloud
  - terraform validate dns/gcloud -var email="email@example.com" -var token="1234"

before_deploy:
  - git reset --hard
  - ./release.sh $(git describe --tags --abbrev=0)
deploy:
  provider: releases
  api_key:
    secure: "wLQ3PPaOxDbroF9bih+JlMJJjuq2gNoYHjWKHuPeNPgs2F07yseSg+OKeutgXGT+ncxSZx/Xsm8pYiFt1mFSJdQNspFsvAA+EiaHqC3P2Erchbo8JYTCUT1KwKqKLq0voH6yuQRDUiZnKVGde1r/ULiIKnVLnVI2ONVpvy+vy4JYA4W1wD6QopC3lhhlJIyOI+bA+yoA3e7iKrsex/g1Ef70QVeuV7KCPPbPHivRRU0XK3yrbMwvEKtV0Mu1sGGhzTumYOQ41gqs1WnUD4dmlNTJY4wJlz/oXBC+An8Miz1a7vppExWyJvWJwa6+Buy0BS3FSb9HXPaO8yfoJUmYxXR3PaBPqHnWXiATZIkCA1mjajgWu59seP7LRbrRqBKhEwEY+nKm6vxg9eVUp4Sq4Y3iJp8gv+mnjCb/VMP7xzzARSDU2bRTg0xBCkRGFvEtqUzbN1xPSMsBG0h4eh7tRZCX7AV5qlZi1OdSR7u4kB1qnCdnhbTyz5XH6IMOpta38Uz2270fYXva+jZ48wp/rcxZX5Uz7luYLTocaMltG1lDN+6QdPhC+RWqNd+WZlKE8LkvE2K20OgG6J9rtIFH4MG4xfbGBM1R5dU/jsVcatiy35L/qQ3gPWbTW4z6N13EsZmCh8LqnXQ3x5jLy89sJvWThTwokVghYiGuFuxZZMI="
  draft: true
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    tags: true
