packages:
  - ipa-client
  - libsss_autofs
  - cvmfs
  - cvmfs-config-default
  - cvmfs-auto-setup
  - nfs-utils
  - python36  
  - git
  - pciutils

runcmd:
  # rsyslog
  - sudo sed -i 's/^#\*.\* @@remote-host:514/\*.\* @@mgmt01:514/g' /etc/rsyslog.conf
  - systemctl restart rsyslog
  # NFS
  - setsebool -P use_nfs_home_dirs 1
  - mkdir -p /project /scratch /localscratch
  - echo "mgmt01:/home      /home      nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - echo "mgmt01:/project   /project   nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - echo "mgmt01:/scratch   /scratch   nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - echo "mgmt01:/etc/slurm /etc/slurm nfs rw,noatime,nolock,hard,tcp 0 0" >> /etc/fstab
  - mount -a
  # CVMFS
  - rpm --import https://git.computecanada.ca/cc-cvmfs-public/cvmfs-config/raw/master/RPM-GPG-KEY-CC-CVMFS-1
  - rpm -U https://git.computecanada.ca/cc-cvmfs-public/cvmfs-config/raw/master/Packages/cvmfs-config-computecanada-latest.noarch.rpm
  - systemctl restart autofs
  # Nvidia driver
  - bash /root/nvidia-driver.sh
  # slurmd
  - yum install -y slurm-slurmd
  - flock /etc/slurm/slurm.conf.lock bash /root/update_slurm.sh
  - systemctl enable slurmd
  - systemctl start  slurmd

write_files:
  - content: |
        #!/bin/bash
        # Add node to slurm.conf
        sed -i "/^NodeName=$(hostname -s)/ d" /etc/slurm/slurm.conf
        sed -i "/# NODE CONFIGURATIONS/a $(slurmd -C | head -n 1)" /etc/slurm/slurm.conf
        # Remove node from unknown state node range
        HOST_UNK_LIST=$(comm -3 <(scontrol show hostname node[1-100] | sort) <(grep -P -o 'NodeName=\K(node[0-9]{1,})' /etc/slurm/slurm.conf | sort) | paste -d, -s)
        HOST_UNK_RANGE=$(scontrol show hostlistsorted $HOST_UNK_LIST)
        sed -i -r "s/(NodeName=)(node\[[0-9-]*\])/\1$HOST_UNK_RANGE/g" /etc/slurm/slurm.conf
        # Force slurmctld reconfiguration
        scontrol reconfigure
    path: /root/update_slurm.sh
  - content: |
        if [[ $UID -ne 0 ]]; then
          if [[ -r /cvmfs/soft.computecanada.ca/config/profile/bash.sh ]]; then
            source /cvmfs/soft.computecanada.ca/config/profile/bash.sh
          fi
        fi
    path: /etc/profile.d/z-00-computecanada.sh
  - path: /root/freeipa.sh
    permissions: 0700
    content: |
        #!/bin/bash
        hostnamectl set-hostname ${hostname}.${domain_name}
        systemctl is-active --quiet NetworkManager
        IS_RUNNING=$?
        if [ $IS_RUNNING -eq 0 ]; then
            systemctl stop NetworkManager
        fi
        sed -i "/nameserver/c\nameserver ${mgmt01_ip}" /etc/resolv.conf
        sed -i "/search/c\search ${domain_name}" /etc/resolv.conf
        chattr +i /etc/resolv.conf
        if [ $IS_RUNNING -eq 0 ]; then
            systemctl start NetworkManager
        fi
        until ping -c1 mgmt01 &>/dev/null; do :; done
        sleep 30
        ipa-client-install --mkhomedir --ssh-trust-dns \
                           --enable-dns-updates \
                           --unattended -p admin \
                           -w ${admin_passwd}
  - path: /etc/cvmfs/default.local
    content: |
        CVMFS_REPOSITORIES="cvmfs-config.computecanada.ca"
        CVMFS_QUOTA_LIMIT=4450
        CVMFS_HTTP_PROXY="http://mgmt01:3128"

  - path: /root/nvidia-driver.sh
    permissions: 0700
    content: |
        #!/bin/bash
        if lspci | grep -q "controller: NVIDIA" ; then
          for VERSION in `ls /cvmfs/soft.computecanada.ca/nix/lib/libcuda.so* | grep -Po "(?<=\.)[0-9]+\.[0-9]+" | sort -rn`
          do
            if yum install -y -q kmod-nvidia-$VERSION; then
              break
            fi
          done
          reboot
        fi

