#cloud-config
packages:
  - git
  - pciutils
  - unzip

users:
  - name: ${sudoer_username}
    groups: adm, wheel, systemd-journal
    homedir: /${sudoer_username}
    selinux_user: unconfined_u
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
%{ for key in ssh_authorized_keys ~}
      - ${key}
%{ endfor ~}

runcmd:
  - restorecon -R /${sudoer_username}
  - "(echo -e '\nHostKeyAlgorithms ssh-rsa\n' >> /etc/ssh/sshd_config && systemctl restart sshd)"
  - yum upgrade -y
  - yum -y install https://yum.puppet.com/puppet6-release-el-$(grep -oP 'VERSION_ID="\K[^"]+' /etc/os-release).noarch.rpm
  - yum -y install puppet-agent-6.18.0
  - /opt/puppetlabs/bin/puppet config set certname ${node_name}
  - /opt/puppetlabs/bin/puppet config set waitforcert 15s
  - /opt/puppetlabs/bin/puppet config set report false
  - /opt/puppetlabs/bin/puppet config set postrun_command /opt/puppetlabs/bin/postrun
  - install -m 700 /dev/null /opt/puppetlabs/bin/postrun
  - systemctl enable puppet
  - systemctl disable kdump
  - sed -i 's/crashkernel=auto/crashkernel=no/' /etc/default/grub
  - sed -i 's/GRUB_CMDLINE_LINUX="[^"]*/& nouveau.modeset=0 rd.driver.blacklist=nouveau/' /etc/default/grub
  - grub2-mkconfig -o /boot/grub2/grub.cfg
  # Remove all ifcfg configuration files that have no corresponding network interface in ip link show.
  - for i in /etc/sysconfig/network-scripts/ifcfg-*; do if ! ip link show | grep -q "$${i##*-}:"; then rm -f $i; fi; done

write_files:
  - content: |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ${puppetmaster_ip} puppet
    path: /etc/hosts
    permissions: "0644"
  - content: |
      facts : {
        blocklist : [ "EC2" ],
      }
    path: /etc/puppetlabs/facter/facter.conf
    permissions: "0644"
  - content: |
      ---
      custom_attributes:
        1.2.840.113549.1.9.7: "${puppetmaster_password}"
    path: /etc/puppetlabs/puppet/csr_attributes.yaml
    permissions: "0640"

disable_ec2_metadata: false
timezone: "UTC"
fqdn: "${node_name}"
output: { all: "| tee -a /var/log/cloud-init-output.log" }
power_state:
  delay: now
  mode: reboot
