# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: build documentation
on: [push, pull_request]
# Declare default permissions as read only.
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: set up Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: '3.10'

    # - name: Markdown Linting Action
    #   uses: avto-dev/markdown-lint@v1.2.0
    #   with:
          # rules: '/lint/rules/changelog.js'
          # config: '/lint/config/changelog.yml'
    #     args: '.'

    - name: install mkdocs + plugins
      run: |
          pip install -r requirements.txt
          pip list | grep mkdocs
          mkdocs --version

    - name: build tutorial
      run: mkdocs build --strict
